name: UltimateClaims
description: UltimateClaims
version: maven-version-number
softdepend: [PlayerPoints, HolographicDisplays, Vault]
main: com.songoda.ultimateclaims.UltimateClaims
author: songoda
api-version: 1.13
commands:
  UltimateClaims:
    description: Reloads the configuration file
    default: true
    aliases: [ucl, claims, claim, c]
    usage: /ultimateclaims reload
permissions:
  ultimateclaims.*:
    description: Inherits all plugin permissions
    children:
      ultimateclaims.bypass: true
  ultimateclaims.bypass:
    description: Allows a player or admin to bypass claim restrictions.
    default: op